[tool.poetry]
name = "blue-iot"
version = "0.1.0"
description = ""
authors = ["KhelifiFekher <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
serial = "^0.0.97"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
